---
title: "Among plots"
author: "Marcel Vaz"
date: "May 2, 2017"
output: html_document
---

# Inter-site growth mortality trade-off
```{r, echo=FALSE, message=FALSE, warning=FALSE}

sites = read.csv("sites.csv",header=T,as.is=T)
cens = read.csv("censuses2.csv",header=T,as.is=T)

#head(cens)
library(smatr)
source("addStar.R")
attach(cens)

# Mortality vs. growth
plot(mort~growth,xlab="Median growth rate (%)",ylab="Median mortality rate (%)",log="xy",ylim=c(0.1,130),pch=16)
addStar(x=growth,y=mort,y0=mLow,y1=mUpp,type="y")
addStar(x=growth,y=mort,x0=gLow,x1=gUpp,type="x")

# Richness
# Mortality vs. richness
plot(mort~rich,xlab="Plot richness",ylab="Median mortality rate (%)",log="xy",ylim=c(0.1,130),pch=16)
addStar(x=rich,y=mort,y0=mLow,y1=mUpp,type="y")

# Growth vs. richness
plot(growth~rich,xlab="Plot richness",ylab="Median growth rate (%)",log="xy",ylim=c(0.5,25),pch=16)
addStar(x=rich,y=growth,y0=gLow,y1=gUpp,type="y")

# G-M slope vs. richness
plot(sl10~rich,xlab="Plot richness",ylab="Growth-mortality slope",log="x",pch=16,main="Saplings")
addStar(x=rich,y=sl10,y0=slL10,y1=slU10,type="y")
plot(sl100~rich,xlab="Plot richness",ylab="Growth-mortality slope",log="x",pch=16,main="Adults")
addStar(x=rich,y=sl100,y0=slL100,y1=slU100,type="y")

detach(cens)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE,fig.width=8,fig.height=5}

# calculates average for each site
mcens = aggregate(cbind(mort,growth,mm10,mg10,mm100,mg100,int10,intU10,intL10,sl10,slU10,slL10,sr10,p10,int100,intU100,intL100,sl100,slU100,slL100,sr100,p100)~site,data=cens,mean)
#mcens

# calculates tree density
sites$treeDens = sites$nTrees/sites$area
#sites

# merge two tables
ff = merge(sites,mcens,all=T)
#ff

attach(ff)

source("graphSites.R")

par(mfrow=c(1,3))
## Growth vs. mortality
# All
graphSites(x=growth,y=mort,type="SMA",log="xy",labX="Growth (%)",labY="Mortality (%)",title="M:1-9.9; G:1-4.9")
# Saplings
graphSites(x=mg10,y=mm10,type="SMA",log="xy",labX="Growth (%)",labY="Mortality (%)",title="Saplings")
# Adults
graphSites(x=mg100,y=mm100,type="SMA",log="xy",labX="Growth (%)",labY="Mortality (%)",title="Adults",jag=1.02)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE,fig.height=10,fig.width=8}
par(mfrow=c(3,2))

## Growth and mortality vs. Precipitation
# Growth
graphSites(x=precip,y=mg10,type="SMA",log="xy",labX="Precipitation",labY="Growth (%)",title="Saplings",legat="topright")
graphSites(x=precip,y=mg100,type="SMA",log="xy",labX="Precipitation",labY="Growth (%)",title="Adults",jag=1.02,legat="bottomright")
# Mortality
graphSites(x=precip,y=mm10,type="SMA",log="y",labX="Precipitation",labY="Mortality (%)",title="Saplings",legat="topright")
graphSites(x=precip,y=mm100,type="SMA",log="y",labX="Precipitation",labY="Mortality (%)",title="Adults",jag=1.02,legat="bottomright")
# G-M slope
graphSites(x=precip,y=sl10,type="SMA",log="",labX="Precipitation",labY="G-M slope",title="Saplings",legat="topright",jag=1.07)
graphSites(x=precip,y=sl100,type="SMA",log="",labX="Precipitation",labY="G-M slope",title="Adults",jag=1.05,legat="bottomleft")

## Growth and mortality vs. Elevation
# Growth
graphSites(x=elev,y=mg10,type="SMA",log="xy",labX="Elevation",labY="Growth (%)",title="Saplings",legat="topright")
graphSites(x=elev,y=mg100,type="SMA",log="xy",labX="Elevation",labY="Growth (%)",title="Adults",jag=1.02,legat="bottomright")
# Mortality
graphSites(x=elev,y=mm10,type="SMA",log="y",labX="Elevation",labY="Mortality (%)",title="Saplings",legat="topright")
graphSites(x=elev,y=mm100,type="SMA",log="y",labX="Elevation",labY="Mortality (%)",title="Adults",jag=1.02,legat="bottomright")
# G-M slope
graphSites(x=elev,y=sl10,type="SMA",log="",labX="Elevation",labY="G-M slope",title="Saplings",legat="topright",jag=1.07)
graphSites(x=elev,y=sl100,type="SMA",log="",labX="Elevation",labY="G-M slope",title="Adults",jag=1.05,legat="bottomleft")

## Growth and mortality vs. Richness
graphSites(x=richness,y=mg10,type="SMA",log="xy",labX="Richness",labY="Growth (%)",title="Saplings",legat="topright")
graphSites(x=richness,y=mg100,type="SMA",log="xy",labX="Richness",labY="Growth (%)",title="Adults",jag=1.02,legat="bottomright")
# Mortality
graphSites(x=richness,y=mm10,type="SMA",log="xy",labX="Richness",labY="Mortality (%)",title="Saplings",legat="topright")
graphSites(x=richness,y=mm100,type="SMA",log="xy",labX="Richness",labY="Mortality (%)",title="Adults",jag=1.02,legat="bottomright")
# G-M slope
graphSites(x=richness,y=sl10,type="SMA",log="x",labX="Richness",labY="G-M slope",title="Saplings",legat="topright",jag=1.07)
graphSites(x=richness,y=sl100,type="SMA",log="x",labX="Richness",labY="G-M slope",title="Adults",jag=1.05,legat="bottomleft")

## Growth and mortality vs. Dry season Length
graphSites(x=drySeason,y=mg10,type="SMA",log="y",labX="Dry season length",labY="Growth (%)",title="Saplings",legat="topleft")
graphSites(x=drySeason,y=mg100,type="SMA",log="y",labX="Dry season length",labY="Growth (%)",title="Adults",jag=1.02,legat="bottomright")
# Mortality
graphSites(x=drySeason,y=mm10,type="SMA",log="y",labX="Dry season length",labY="Mortality (%)",title="Saplings",legat="topleft")
graphSites(x=drySeason,y=mm100,type="SMA",log="y",labX="Dry season length",labY="Mortality (%)",title="Adults",jag=1.02,legat="bottomright")
# G-M slope
graphSites(x=drySeason,y=sl10,type="SMA",log="",labX="Dry season length",labY="G-M slope",title="Saplings",legat="topright",jag=1.07)
graphSites(x=drySeason,y=sl100,type="SMA",log="",labX="Dry season length",labY="G-M slope",title="Adults",jag=1.05,legat="bottomleft")

## Growth and mortality vs. Tree density
graphSites(x=treeDens,y=mg10,type="SMA",log="xy",labX="Tree density (ha-1)",labY="Growth (%)",title="Saplings",legat="topleft")
graphSites(x=treeDens,y=mg100,type="SMA",log="xy",labX="Tree density (ha-1)",labY="Growth (%)",title="Adults",jag=1.02,legat="bottomright")
# Mortality
graphSites(x=treeDens,y=mm10,type="SMA",log="xy",labX="Tree density (ha-1)",labY="Mortality (%)",title="Saplings",legat="topleft")
graphSites(x=treeDens,y=mm100,type="SMA",log="xy",labX="Tree density (ha-1)",labY="Mortality (%)",title="Adults",jag=1.02,legat="bottomright")
# G-M slope
graphSites(x=treeDens,y=sl10,type="SMA",log="x",labX="Tree density (ha-1)",labY="G-M slope",title="Saplings",legat="topright",jag=1.07)
graphSites(x=treeDens,y=sl100,type="SMA",log="x",labX="Tree density (ha-1)",labY="G-M slope",title="Adults",jag=1.05,legat="bottomleft")

detach(ff)

par(mfrow=c(1,1))

```

